import React, { useEffect, useRef } from 'react';
import { TranslatedPage } from '../types';
import { Download, ChevronLeft, ChevronRight, RefreshCw, FileCheck } from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface TranslationViewerProps {
  pages: TranslatedPage[];
  onDownload: () => void;
  onReset: () => void;
}

export const TranslationViewer: React.FC<TranslationViewerProps> = ({ pages, onDownload, onReset }) => {
  const [activePageIndex, setActivePageIndex] = React.useState(0);
  const contentRef = useRef<HTMLDivElement>(null);
  const [isGeneratingPdf, setIsGeneratingPdf] = React.useState(false);
  const [downloadStatus, setDownloadStatus] = React.useState('');

  const activePage = pages[activePageIndex];

  const handleDownloadPDF = async () => {
    setIsGeneratingPdf(true);
    setDownloadStatus('Initializing PDF engine...');
    
    try {
      const doc = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4',
      });

      setDownloadStatus('Loading Chinese fonts (this may take a moment)...');

      // Try to load a Chinese font to support text rendering. 
      // Using Noto Sans CJK SC from a reliable raw source.
      try {
        const fontUrl = 'https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Simplified/NotoSansCJKsc-Regular.otf';
        const response = await fetch(fontUrl);
        if (response.ok) {
          const buffer = await response.arrayBuffer();
          const binary = new Uint8Array(buffer).reduce((data, byte) => data + String.fromCharCode(byte), '');
          const base64Font = window.btoa(binary);
          
          doc.addFileToVFS('NotoSansCJKsc-Regular.otf', base64Font);
          doc.addFont('NotoSansCJKsc-Regular.otf', 'NotoSansSC', 'normal');
          doc.setFont('NotoSansSC');
        } else {
          console.warn("Could not fetch font, falling back to standard fonts (Chinese may not render correctly in text mode).");
        }
      } catch (fontError) {
        console.warn("Font loading failed, proceeding with image-based fallback where possible.", fontError);
      }

      setDownloadStatus('Generating pages...');

      // Add Title Page
      doc.setFontSize(20);
      // Check if font was added, otherwise use default
      if (doc.getFontList()['NotoSansSC']) {
        doc.setFont('NotoSansSC');
      }
      doc.text("Translated Document", 105, 20, { align: "center" });
      doc.setFontSize(12);
      doc.text("Generated by PDF Translate Pro", 105, 30, { align: "center" });
      doc.addPage();

      // We use a temporary container to render each page
      const container = document.createElement('div');
      container.style.position = 'absolute';
      container.style.top = '-9999px';
      container.style.width = '210mm'; // A4 width
      // Ensure height is auto to capture full content
      container.style.minHeight = '297mm'; 
      container.style.height = 'auto';
      container.style.padding = '20px';
      container.style.background = 'white';
      container.style.overflow = 'visible'; // Prevent clipping
      // Ensure the font is available in the DOM for html2canvas capture
      container.style.fontFamily = '"Inter", "Noto Sans SC", "SimSun", "Arial", sans-serif'; 
      document.body.appendChild(container);

      // Inject styles into the container for PDF generation consistency
      const style = document.createElement('style');
      style.innerHTML = `
        table { width: 100%; border-collapse: collapse; margin-bottom: 1em; }
        th, td { border: 1px solid #000; padding: 6px; text-align: left; font-size: 12px; }
        th { background-color: #f0f0f0; font-weight: bold; }
        img { max-width: 100%; height: auto; }
        sup { vertical-align: super; font-size: smaller; }
        sub { vertical-align: sub; font-size: smaller; }
        .image-placeholder { padding: 20px; border: 1px dashed #ccc; background: #f9f9f9; text-align: center; color: #666; font-style: italic; }
        /* Ensure no overflow issues */
        * { box-sizing: border-box; }
      `;
      container.appendChild(style);

      const pdfPageWidth = doc.internal.pageSize.getWidth();
      const pdfPageHeight = doc.internal.pageSize.getHeight();

      for (let i = 0; i < pages.length; i++) {
         if (i > 0) doc.addPage();
         
         setDownloadStatus(`Processing page ${i + 1} of ${pages.length}...`);
         const page = pages[i];
         
         // Render HTML into the container
         // Create a wrapper div for the content
         const contentDiv = document.createElement('div');
         contentDiv.innerHTML = page.translatedHtml;
         container.appendChild(contentDiv);
         
         // Wait a brief moment for images/styles to settle
         await new Promise(resolve => setTimeout(resolve, 100));

         // Use html2canvas to snapshot the element. 
         const canvas = await html2canvas(container, {
           scale: 2, // Higher scale for better quality
           useCORS: true,
           logging: false,
           width: 794, // A4 width in px at 96dpi (approx)
           windowWidth: 1024, // Ensure viewport is wide enough
           height: container.scrollHeight // Capture full height explicitly
         });

         // Balanced quality setting (0.75) to maintain clarity while reducing PDF file size
         const imgData = canvas.toDataURL('image/jpeg', 0.75);
         const imgProps = doc.getImageProperties(imgData);
         
         // Logic to Scale-to-Fit Page
         // 1. Calculate the dimensions if we fit by width
         const widthRatio = pdfPageWidth / imgProps.width;
         let finalWidth = pdfPageWidth;
         let finalHeight = imgProps.height * widthRatio;
         let xPos = 0;
         let yPos = 0;

         // 2. If the resulting height is taller than the page, fit by height instead
         if (finalHeight > pdfPageHeight) {
            const heightRatio = pdfPageHeight / imgProps.height;
            finalHeight = pdfPageHeight;
            finalWidth = imgProps.width * heightRatio;
            // Center horizontally
            xPos = (pdfPageWidth - finalWidth) / 2;
         }
         
         doc.addImage(imgData, 'JPEG', xPos, yPos, finalWidth, finalHeight);
         
         // Clear content for next page
         container.removeChild(contentDiv);
      }

      document.body.removeChild(container);
      
      setDownloadStatus('Saving file...');
      doc.save('translated_document.pdf');

    } catch (e) {
      console.error("PDF Gen Error", e);
      alert("Could not generate PDF. Error: " + (e instanceof Error ? e.message : String(e)));
    } finally {
      setIsGeneratingPdf(false);
      setDownloadStatus('');
    }
  };

  return (
    <div className="flex flex-col h-full bg-gray-50">
      {/* Toolbar */}
      <div className="bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between shadow-sm shrink-0 z-10">
        <div className="flex items-center gap-4">
          <button 
            onClick={onReset}
            className="flex items-center gap-2 text-gray-600 hover:text-gray-900 text-sm font-medium transition-colors"
          >
            <RefreshCw size={16} />
            New Translation
          </button>
          <div className="h-4 w-px bg-gray-300"></div>
          <span className="text-sm text-gray-500">
            Page {activePageIndex + 1} of {pages.length}
          </span>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => setActivePageIndex(p => Math.max(0, p - 1))}
            disabled={activePageIndex === 0}
            className="p-2 hover:bg-gray-100 rounded-lg disabled:opacity-30 disabled:cursor-not-allowed transition-colors text-gray-600"
          >
            <ChevronLeft size={20} />
          </button>
          
          <button
            onClick={() => setActivePageIndex(p => Math.min(pages.length - 1, p + 1))}
            disabled={activePageIndex === pages.length - 1}
            className="p-2 hover:bg-gray-100 rounded-lg disabled:opacity-30 disabled:cursor-not-allowed transition-colors text-gray-600"
          >
            <ChevronRight size={20} />
          </button>

          <div className="h-4 w-px bg-gray-300 mx-2"></div>

          <button
            onClick={handleDownloadPDF}
            disabled={isGeneratingPdf}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg shadow-sm transition-all text-sm font-medium disabled:opacity-70 w-48 justify-center"
          >
            {isGeneratingPdf ? (
                <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
            ) : (
                <Download size={16} />
            )}
            {isGeneratingPdf ? (downloadStatus ? 'Processing...' : 'Building PDF...') : 'Download PDF'}
          </button>
        </div>
      </div>
      
      {isGeneratingPdf && downloadStatus && (
        <div className="absolute top-16 left-1/2 transform -translate-x-1/2 bg-gray-800 text-white px-4 py-2 rounded-full text-sm shadow-lg z-50 animate-fade-in">
          {downloadStatus}
        </div>
      )}

      {/* Split View Content */}
      <div className="flex-1 overflow-hidden flex relative">
        
        {/* Left: Original */}
        <div className="w-1/2 bg-gray-100 overflow-y-auto p-8 border-r border-gray-200">
          <div className="max-w-full bg-white shadow-lg rounded-sm min-h-[800px] relative">
            <div className="absolute top-0 left-0 bg-blue-600 text-white text-xs px-3 py-1 rounded-br-lg z-10 font-semibold uppercase tracking-wider">
              Original
            </div>
            {activePage?.originalImage ? (
               <img 
                 src={activePage.originalImage} 
                 alt={`Page ${activePage.pageNumber}`}
                 className="w-full h-auto block"
               />
            ) : (
              <div className="h-full flex items-center justify-center text-gray-400">
                Loading page...
              </div>
            )}
          </div>
        </div>

        {/* Right: Translated */}
        <div className="w-1/2 bg-white overflow-y-auto p-8">
          <div className="max-w-full bg-white min-h-[800px] relative border border-gray-100 shadow-sm rounded-sm p-8 prose prose-sm max-w-none prose-headings:text-gray-800 prose-p:text-gray-600">
             <style>{`
              .pdf-translated-content table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 1em;
                margin-bottom: 1em;
                border: 1px solid #e2e8f0;
              }
              .pdf-translated-content th, .pdf-translated-content td {
                border: 1px solid #cbd5e1;
                padding: 8px;
                text-align: left;
              }
              .pdf-translated-content th {
                background-color: #f1f5f9;
                font-weight: 600;
              }
              .image-placeholder {
                 background: #f9fafb;
                 border: 1px dashed #cbd5e1;
                 border-radius: 8px;
                 padding: 24px;
                 text-align: center;
                 color: #6b7280;
                 margin: 16px 0;
                 font-size: 0.9em;
              }
              /* Error state styling */
              .error-container {
                padding: 1rem;
                border: 1px solid #fecaca;
                background-color: #fef2f2;
                border-radius: 0.375rem;
                color: #991b1b;
              }
            `}</style>

            <div className="absolute top-0 right-0 bg-green-600 text-white text-xs px-3 py-1 rounded-bl-lg z-10 font-semibold uppercase tracking-wider">
              Chinese Translation
            </div>
            
            {activePage?.status === 'translating' ? (
              <div className="flex flex-col items-center justify-center h-[600px] space-y-4">
                 <div className="relative w-20 h-20">
                    <div className="absolute top-0 left-0 w-full h-full border-4 border-blue-100 rounded-full"></div>
                    <div className="absolute top-0 left-0 w-full h-full border-4 border-blue-500 rounded-full border-t-transparent animate-spin"></div>
                 </div>
                 <p className="text-gray-500 font-medium animate-pulse">Analyzing layout & translating...</p>
              </div>
            ) : activePage?.status === 'error' ? (
              <div className="flex flex-col items-center justify-center h-[600px] text-center p-8">
                <div className="bg-red-100 p-4 rounded-full mb-4">
                   <div className="text-red-500">⚠️</div>
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-2">Translation Failed</h3>
                <p className="text-gray-600 mb-6 max-w-md">
                  We encountered an error processing this page. It might be due to complex layout or connection issues.
                </p>
                {activePage.errorMessage && (
                   <div className="mb-6 p-3 bg-gray-100 rounded text-xs text-left w-full max-w-md overflow-auto max-h-32 font-mono text-gray-700">
                      {activePage.errorMessage}
                   </div>
                )}
                <button 
                  onClick={() => {
                     // We need a way to trigger retry from here. 
                     // Since retry logic is in App.tsx, ideally we pass a retry handler.
                     // For now, we display the error clearly.
                     alert("Please try reloading the document or re-uploading.");
                  }}
                  className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg font-medium transition-colors"
                >
                  Retry Document
                </button>
              </div>
            ) : (
              <div 
                dangerouslySetInnerHTML={{ __html: activePage.translatedHtml }} 
                className="pdf-translated-content font-[system-ui] leading-relaxed"
              />
            )}
          </div>
        </div>

      </div>
    </div>
  );
};